CREATE TABLE MSVC_BASE.MB_COURSES (
    COURSE_ID           NUMBER,
    COURSE_NAME         VARCHAR2(250),
    STATUS              VARCHAR2(2),
    CREATION_DATE       DATE,
    LAST_UPDATE_DATE    DATE,
    ACTIVE              NUMBER
);
ALTER TABLE MSVC_BASE.MB_COURSES ADD CONSTRAINT MB_COURSE_PK PRIMARY KEY (COURSE_ID);
CREATE SEQUENCE MSVC_BASE.SEQ_COURSES MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
COMMENT ON TABLE MSVC_BASE.MB_COURSES IS 'Tabla que contiene los cursos';
COMMENT ON COLUMN MSVC_BASE.MB_COURSES.COURSE_ID IS 'ID Unico de la llave';
COMMENT ON COLUMN MSVC_BASE.MB_COURSES.COURSE_NAME IS 'Nombre completo del curso';
COMMENT ON COLUMN MSVC_BASE.MB_COURSES.STATUS IS 'Estatus en el que se encuentra el curso';
COMMENT ON COLUMN MSVC_BASE.MB_COURSES.CREATION_DATE IS 'Fecha de alta de registro';
COMMENT ON COLUMN MSVC_BASE.MB_COURSES.LAST_UPDATE_DATE IS 'Fecha de ultima actualizacion';
COMMENT ON COLUMN MSVC_BASE.MB_COURSES.ACTIVE IS 'Indica si el registro esta activo';