CREATE TABLE MSVC_BASE.MB_USERS (
    USER_ID             NUMBER,
    USER_NAME           VARCHAR2(250),
    USER_EMAIL          VARCHAR2(250),
    PASSWORD            VARCHAR2(250),
    CREATION_DATE       DATE,
    LAST_UPDATE_DATE    DATE,
    ACTIVE              NUMBER
);
ALTER TABLE MSVC_BASE.MB_USERS ADD CONSTRAINT MB_USER_PK PRIMARY KEY (USER_ID);
CREATE SEQUENCE MSVC_BASE.SEQ_USERS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;
COMMENT ON TABLE MSVC_BASE.MB_USERS IS 'Tabla que contiene los usuarios';
COMMENT ON COLUMN MSVC_BASE.MB_USERS.USER_ID IS 'ID Unico de la llave';
COMMENT ON COLUMN MSVC_BASE.MB_USERS.USER_NAME IS 'Nombre completo personal del usuario';
COMMENT ON COLUMN MSVC_BASE.MB_USERS.USER_EMAIL IS 'Correo electronico';
COMMENT ON COLUMN MSVC_BASE.MB_USERS.PASSWORD IS 'Credenciales de acceso';
COMMENT ON COLUMN MSVC_BASE.MB_USERS.CREATION_DATE IS 'Fecha de alta de registro';
COMMENT ON COLUMN MSVC_BASE.MB_USERS.LAST_UPDATE_DATE IS 'Fecha de ultima actualizacion';
COMMENT ON COLUMN MSVC_BASE.MB_USERS.ACTIVE IS 'Indica si el registro esta activo';